version: '3'

services:
  db:
    image: mysql:5.7
    container_name: umi_web
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - ./mysql:/var/lib/mysql
    command: mysqld --sql_mode=""
  web:
    image: ss_web:last
    build: ./
    container_name: umi_mysql
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    links:
      - db:mysql
    stdin_open: true
    tty: true